############## APP CONFIGURATION ##############
app:
  timezone: Europe/Rome
  service:
    sp:
      url: http://localhost:8082/sp
############## SPRING CONFIGURATION ##############
spring:
  kafka:
    bootstrap-servers: localhost:9092
    listener:
      log-container-config: false
    producer:
      retries: 1
############## SERVER CONFIGURATION ##############
server:
  port: 8081
  servlet:
    context-path: /se

